
DROP TEMPORARY TABLE IF EXISTS ab;
CREATE TEMPORARY TABLE IF NOT EXISTS ab(
c INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Jan INT, Feb INT)
;
INSERT INTO ab (Jan) VALUES (1), (2);	
select * from ab; *

